---

log_batch_size: 100_000
solr_version: 7.4.0
log_file: /var/log/traject/traject_prod.log
log_error_file: /var/log/traject/traject_error_prod.log
solr_writer_commit_on_close: true
reader_class_name: Traject::MarcCombiningReader
marc4j_reader_permissive: true
marc4j_reader_source_encoding: UTF-8
processing_thread_pool: 7
commit_timeout: 900