---

solr_url: http://localhost:8983/solr/psul_blacklight
log_batch_size: 100_000
solr_version: 7.4.0
log_file: log/traject.log
log_error_file: log/traject_error.log
solr_writer_commit_on_close: true
reader_class_name: Traject::MarcCombiningReader
marc4j_reader_permissive: true
marc4j_reader_source_encoding: UTF-8
processing_thread_pool: 5
commit_timeout: 10000